core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from .forms import LoginForm
from . import views
app_name = 'core'


urlpatterns = [
    path('', views.home, name='home'),
    path('registro/', views.signup, name='registro'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
]

eccomerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from core.views import home, signup

urlpatterns = [
    path('', include('core.urls')),
    path('detalhes/', include('item.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

item/urls.py
from django.urls import path
from . import views
app_name = 'item'

urlpatterns = [
     path('add/', views.newAdd, name="add"),
     path('<int:pk>/', views.detail, name='detalhes'),
     path('<int:pk>/delete/', views.delete, name='delete'),
     path('<int:pk>/edit/', views.newEdit, name='edit')
]

core/models.py
from django.db import models

dashboard/models.py
from django.db import models

# Create your models here.

item/models.py
from django.db import models
from django.contrib.auth.models import User
# Categoria
class Categoria(models.Model):
    name = models.CharField(max_length=225)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categorias'

    def __str__(self):
        return self.name

class Item(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    categoria = models.ForeignKey(Categoria, related_name="items", on_delete=models.CASCADE)
    price = models.FloatField()
    image = models.ImageField(upload_to='item_images', blank=True, null=True)
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name="items", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm): 
    username   = forms.CharField(widget=forms.TextInput())
    password   = forms.CharField(widget=forms.PasswordInput())
    

class RegistroForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    username    = forms.CharField(widget=forms.TextInput())
    email       = forms.CharField(widget=forms.EmailInput())
    password1   = forms.CharField(widget=forms.PasswordInput())
    password2   = forms.CharField(widget=forms.PasswordInput())

core/views.py
from django.shortcuts import render, redirect
from item.models import Categoria, Item
from .forms import RegistroForm

# home page
def home(request):
    items = Item.objects.filter(is_sold=False)[0:6]
    Categorias = Categoria.objects.all()
    return render(request, 'core/index.html', {
        'categorias': Categorias,
        'items': items,
    })

def signup(request):
    if request.method == 'POST':
        form = RegistroForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/login/')
    else:
        form = RegistroForm()

    return render(request, 'core/registro.html', {
        'form': form
    })

dashboard/views.py
from django.shortcuts import render

# Create your views here.

item/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Item
from .form import NewItem, EditItem

# display each item
def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    related_items = Item.objects.filter(categoria=item.categoria, is_sold=False).exclude(pk=pk)[0:3]
    return render(request, 'item/detail.html', {
        'item': item,
        'related_items': related_items
    })


@login_required
def newAdd(request):
    if request.method == 'POST':
        form = NewItem(request.POST, request.FILES)

        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            item.save()

            return redirect('item:detail.html', pk=item.id)
    else:
        form = NewItem()

    return render(request, 'item/form.html', {
        'form': form,
        'title': 'Novo Item'
    })

@login_required
def newEdit(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    if request.method == 'POST':
        form = EditItem(request.POST, request.FILES, instance=item)
        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            item.save()
            return redirect('item:detail.html', pk=item.id)
    else:
        form = EditItem(instance=item)
    return render(request, 'item/form.html', {
        'form': form,
        'title': 'Editar Item'
    })


def delete(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    item.delete()

    return redirect('item:detail.html')

core/templates/core/base.html
{% load static %}
<!DOCTYPE HTML>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
        <title>{%block title %}{% endblock %} | Eccomerce App</title>
    </head>
    <body>
        <div>
            {%block content%}
            {%endblock%}
        </div>

    </body>
</html>

core/templates/core/index.html
{% extends "core/base.html" %}
{%block title%}Home Page{%endblock%}
{% block content%}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          {%if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Messages</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Dashboard</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="#">novo item</a>
          </li>
          {%else%}
          <li class="nav-item">
            <a class="nav-link active" href="#">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="#">Registrar</a>
          </li>
          {%endif%}
          </ul>
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>
{%for item in items%}
<a href="{% url 'item:detalhes' item.id%}">
<img src="{{item.image.url}}">
<p>{{item.name}}</p>
<p>{{item.price}}</p>
</a>
{%endfor%}
<div>
    {%for category in categorias%}
<p>{{category.name}}</p>
<p>{{category.items.count }}</p>

    {%endfor%}
</div>
{%endblock%}

core/templates/core/login.html
{% extends "core/base.html" %}
{%block title%}Login{%endblock%}
{% block content%}

<section>
    <div class="container mt-5 pt-5">
        <div class="row">
            <div class="col-12 col-sm-8 col-md-6 m-auto">
                <div class="card border-0 shadow">
                    <div class="card-body">
                        <form method="post" action=".">
                            {% csrf_token %}
                            <label>Email</label>
                            <input type="text" class="form-control my-4 py-4" placeholder="username" name="username">
                            <label>Password</label>
                            <input type="password" class="form-control my-4 py-4" placeholder="digite password" name="password">
                            {% if form.errors or form.non_field_errors %}
                            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                                {% for field in form %}
                                    {{ field.errors }}
                                {% endfor %}
                
                                {{ form.non_field_errors }}
                            </div>
                        {% endif %}
                        <button class="btn btn-primary">Registrar</button> 
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

  {%endblock%}

core/templates/core/registro.html
{% extends "core/base.html" %}
{%block title%}Registro{%endblock%}
{% block content%}

<section>
    <div class="container mt-5 pt-5">
        <div class="row">
            <div class="col-12 col-sm-8 col-md-6 m-auto">
                <div class="card border-0 shadow">
                    <div class="card-body">
                        <form method="post" action=".">
                            {% csrf_token %}
                            <input type="text" class="form-control my-4 py-4" placeholder="username" name="username">
                           
                            <input type="email" class="form-control my-4 py-4" placeholder="email" name="email">
                            
                            <input type="password" class="form-control my-4 py-4" placeholder="digite password" name="password1">
                            
                            <input type="password" class="form-control my-4 py-4" placeholder="repetir a password" name="password2">
                            {% if form.errors or form.non_field_errors %}
                            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                                {% for field in form %}
                                    {{ field.errors }}
                                {% endfor %}
                
                                {{ form.non_field_errors }}
                            </div>
                        {% endif %}
                        <button class="btn btn-primary">Registrar</button> 
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

  {%endblock%}

item/templates/item/detail.html
{%extends 'core/base.html'%}
{%block title%}{{item.name}}{%endblock%}
{%block content%}
<div class="container mx-auto">
    <h1>{{item.name}}</h1>
    <img class="w-auto" src="{{item.image.url}}">
</div>
<div class="container mx-auto">
{%for item in related_items%}
<a href="{% url 'item:detalhes' item.id%}">
<img src="{{item.image.url}}">
<p>{{item.name}}</p>
<p>{{item.price}}</p>

{%if request.user == item.created_by %}
<a type="submit" href="{%url 'item:edit' item.id %}" class="btn-success">editar</a>
<a type="submit" href="{%url 'item:delete' item.id %}" class="btn-danger">apagar</a>
{%else%}
<a href="" class="btn btn-success">contactar o vendedor</a>
{%endif%}
</a>
</div>
{%endfor%}
{%endblock%}

item/templates/item/form.html
{% extends "core/base.html" %}
{% block  content %}
<form method="post" action="." enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}

    {% if form.errors or form.non_field_errors %}
    {%for field in form %}
    {{field.errors}}
    {%endfor%}
    {{form.non_field_errors}}
    {%endif%}
    <button type="submit" class="btn btn-success">enviar</button>
    </form>
{% endblock %}